name: satisfaction
description: A collection of customer satisfaction scores and metrics used by businesses to measure and assess customer satisfaction.
version: 1.0.0
repository: https://github.com/0xdir/satisfaction_dart

funding:
  - https://github.com/sponsors/0xdir
topics:
  - data
  - csat
  - nps
  - customer
  - metrics

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0